name: Playwright Tests

on:
  schedule:
    # 15 = Minute (15 past)
    # 8  = Hour (8 AM UTC)
    # * = Every day
    - cron: '15 8 * * *'
    
  workflow_dispatch:

# Trigger: Run on push to main or any pull request
#on:
#  push:
#    branches: [ main, master ]
#  pull_request:
#    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    # 1. Get the code
    - uses: actions/checkout@v4

    # 2. Install Node.js
    - uses: actions/setup-node@v4
      with:
        node-version: 18

    # 3. Install Dependencies (package.json)
    - name: Install dependencies
      run: npm ci

    # 4. Install Playwright Browsers
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # 5. Start the Dummy App (Background Process)
    # Since we don't have a real staging URL yet, we boot up the local HTML file in CI.
    # The '&' runs it in the background so the next step can proceed.
    #- name: Start Local Server
    #  run: npx http-server -p 8080 &

    # 6. Run Playwright Tests
    # We manually inject the BASE_URL here because .env files are gitignored.
    - name: Run Playwright tests
      run: npx playwright test
      env:
        # This overrides the missing config/.env.dev file
        BASE_URL: 'http://localhost:8080'
        ENV: 'ci'

    # 7. Upload Report (Only if tests fail)
    # This lets you download the HTML report from GitHub to debug failures.
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30